name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Gen French PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: './dist/index.html#fr'
          outputFile: './dist/CV Arthur JAOUEN.pdf'
          pdfOptions: '{"format": "A4", "printBackground": true, "preferCSSPageSize": true}'

      - name: Gen English PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: './dist/index.html#en'
          outputFile: './dist/CV Arthur JAOUEN en.pdf'
          pdfOptions: '{"format": "A4", "printBackground": true, "preferCSSPageSize": true}'

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist/'

  deploy:
    needs: build

    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
